version: '3.6'
services:
  node:
<<<<<<< HEAD
    container_name: project_api_node
=======
    container_name: api_node
>>>>>>> 5-comments
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
<<<<<<< HEAD
    container_name: project_api_mongo
=======
    container_name: api_mongo
>>>>>>> 5-comments
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
